### ISSUE TITLE
The font looks very outdated

### ISSUE THREAD

**Issue by LittleVulpix** [SkyzohKey/tox-website#1]
Would it be possible to use the same font already used on tox.chat ? It looks much better; more professional.

**Comment by SkyzohKey** [comment]
The font used is the sans-serif one used on your system. But I plan to follow my mockups and use Exo, maybe I'll look at using the one from tox.chat

**Comment by LittleVulpix** [comment]
![image](https://user-images.githubusercontent.com/8679333/30105489-12a0116c-92f9-11e7-8455-8dc5fdf5d0c9.png)

I guess it just looks pretty terrible. Very dated... so yeah, that would be cool :)

**Comment by SkyzohKey** [comment]
What about these fonts :

![Maven Pro](https://designmodo.com/wp-content/uploads/2012/12/31.jpg)

![Aileron](https://designmodo.com/wp-content/uploads/2016/01/aileron.jpg)

**Comment by LittleVulpix** [comment]
I really like the second one, but both look great!

**Comment by SkyzohKey** [comment]
I guess the second would perfectly fit for headers and titles. While the first one might be nice for body text.
