### ISSUE TITLE
Select a more pleasing colour combination for the website's primary colours

### ISSUE THREAD

**Issue by LittleVulpix** [SkyzohKey/tox-website#5]
The fonts now look a lot better thanks to #1 , but the colours are still not quite there. The sickly green colour is very displeasing for the eye. Possibly inspire yourself from https://designschool.canva.com/blog/website-color-schemes/

**Comment by SkyzohKey** [comment]
What about purple ? It's a trendy colour and it's gender neutral

**Comment by LittleVulpix** [comment]
I guess it depends on what kinda purple we're talking about.

#6f34f5cc for example:

![image](https://user-images.githubusercontent.com/8679333/30156989-663ab8d6-93c1-11e7-9a0c-cb0fbabc241a.png)

But maybe the whole site could use different colours. Not be tied to "white background" etc. I think more people's input is required for this one; but it would be nice if the site didn't burn people's retinas as they tried to read it :D

**Comment by SkyzohKey** [comment]
It looks really fine with that purple variation: `#a560e8`

![](https://i.imgur.com/9lrtrms.png)

**Comment by SkyzohKey** [comment]
Blueish `#007cc3`

![](https://i.imgur.com/cr6vtG8.png)

**Comment by SkyzohKey** [comment]
Another darker purple `#954a97`

![](https://i.imgur.com/q2RfvUh.png)

**Comment by Nyoroon** [comment]
Both blue and dark purple purple looks fine for me, but blue looks "calmer" (reason for many companies to use it maybe? XD).

**Comment by SkyzohKey** [comment]
@nyoroon Yep I like it in blue too :)

Material Indigo 500 `#3F51B5`

![](https://i.imgur.com/jldQFZ6.png)

**Comment by SkyzohKey** [comment]
Yaaaaaaaay!

![](https://i.imgur.com/f5HAC4F.png)

**Comment by SkyzohKey** [comment]
@LittleVulpix does it looks better for you now ?

**Comment by LittleVulpix** [comment]
For me, it looks good - but somehow the buttons look jarring :D just  straight blue... but the rest is great.

**Comment by SkyzohKey** [comment]
Did you tried the live demo ? It looks pretty decent to me, and the features page is live too :)

**Comment by LittleVulpix** [comment]
Well, it looks good enough x3 I say ship it, at worst we'll fix it up later.

**Comment by SkyzohKey** [comment]
It's live on the demo, I've done a lot of work quickly. More to come soon + the backend, before even considering making it to run in production :)
